spring.application.name=smart-inventory-system


spring.datasource.url=jdbc:mysql://localhost:3306/SmartInventoryDB
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud_name= dsm7s0h0u
cloudinary.api_key = 223631394429332
cloudinary.api_secret = oN5y8lgZzamayxdedkr9hDtMKrQ

server.port=5000

